### PR TITLE
the real fix of #52

### PR DESCRIPTION
**Pull request by ickc**

### CODE REVIEW

**Comment by ickc** [comment]
#54 has been targeting the wrong bug. The `git reset --hard` would not messed up anything. The true problem lies in the setup.cfg. That setting will always override the cli option and build a universal wheel.

That explains why the settings in #52 was working in my pantable — I was looking in the wrong place — .travis.yml, setup.py, etc. all works, but I overlooked setup.cfg...

Sorry again.

But in this case you **do not** need to remove the 1.10.1 version on PyPI. Since it is a pasteurized universal wheel. So it didn't break anything for py2 users.

**Comment by ickc** [comment]
I updated the README which causes Travis to run for a while.

**Comment by ickc** [comment]
Just to reassure: [Build #219 - ickc/pantable - Travis CI](https://travis-ci.org/ickc/pantable/builds/192520889) confirms that the wheels are good: py2/py3 builds are installing the respective wheels.

**Comment by sergiocorreia** [comment]
Great, hopefully the py2 build is now fixed for good

**Pull request merged**
