### PR TITLE
travis: pasteurize ignore panflute/version.py

### PR DESCRIPTION
**Pull request by ickc**
Bug fix:

currently, if the local machine has not installed `future`, `pip install panflute` will be failed. The reason is basically because panflute/version.py is pasteurized (which import future), and is used in setup.py.

### CODE REVIEW

**Comment by ickc** [comment]
The 2nd commit is to change the way the filters are copied to $DATADIR. I noticed that the previous script (that copies in parallel) occasionally causes a failed build.

**Comment by ickc** [comment]
By the way, I just hit some other bugs relating to unicode again. I'll try to hunt them down.

**Comment by ickc** [comment]
One bug that puzzles me is (from [Job #157.2 - ickc/pantable - Travis CI](https://travis-ci.org/ickc/pantable/jobs/186016056#L345-L349)):

```python
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/panflute/elements.py", line 726, in __init__
    self.text = check_type(text, str)
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/panflute/utils.py", line 26, in check_type
    raise TypeError(msg)
TypeError: received str but expected <class 'future.types.newstr.newstr'>
```

But when I test it like this:

```python
>>> from __future__ import unicode_literals
>>> from builtins import str
>>> s = str(u'ABCD')
>>> type(s)
<class 'future.types.newstr.newstr'>
>>> isinstance(s, str)
True
```

So an object of `<class 'future.types.newstr.newstr'>` will be recognized as `str`. So I have no idea why that error pops up.

**Comment by sergiocorreia** [comment]
Interesting; I didn't try installing from pip...

About `newst`, it's probably because it's defined as an instance of `str`. I'll replace the type check done in tools with an isinstance check, perhaps this will fix it

**Pull request merged**
