### PR TITLE
setup travis to always deploy on PyPI (#22)

### PR DESCRIPTION
**Pull request by ickc**
Since you use Windows and use GitHub Desktop, I figure it would be easier for you to let Travis deploy to PyPI *everytime*. Only when the version is bumped, it will go through. So effectively Travis will auto deploy to PyPI whenever you change the version and commit. (If the version isn't changed, it won't go through. There's an error but since it is in the deploy stage, the error won't result in a fail build.)

What's done:

- setup Travis' deploy to PyPI
- I also rearrange the `.travis.yml` into a more logical order.
- `setup.py` and `requirements.txt` are setup; in particular, travis can now install the dependency by `pip install -e .[test]`

# Setting up Travis' Environmental Variables

Because I don't have your PyPI password, you need to go into <https://travis-ci.org/sergiocorreia/panflute>:

```
More Options -> Settings -> Environment Variables

Name: pypi_password
Value: <your PyPI password
Display value in build log: OFF
```

This last setting is very important. If it is `OFF` it will be secured and any others won't be able to see/use it.

>By default, the value of these new environment variables is hidden from the export line in the logs. This corresponds to the behavior of encrypted variables in your .travis.yml.
>
>Similarly, we do not provide these values to untrusted builds, triggered by pull requests from another repository.
>
>As an alternative to the web interface, you can also use the CLI’s env command.

Reference: [Environment Variables - Travis CI](https://docs.travis-ci.com/user/environment-variables/)

Since I don't have your password I can't test the whole process. But I have used it in my own repo so it should be fine. I suggest you to test it once and verify it goes through to PyPI though.

### CODE REVIEW

**Comment by ickc** [comment]
I was going to open another pull request, but "use rst on PyPI's website" are also about PyPI's deployment, so I decided to put them together (in the danger of having 1 pull request doing too much things).

This will use pypandoc to output an auxilliary README in reStructureText format for PyPI in other to have proper HTML output. Currently the PyPI page of panflute in [panflute 1.6.3 : Python Package Index](https://pypi.python.org/pypi/panflute/1.6.3) isn't quite nice.

**Comment by sergiocorreia** [comment]
Thanks for the cleanup?

One question: do we still need pandocfilters in requirements, given that we are only using it for testing?

**Comment by ickc** [comment]
is `shutilwhich` needed as well? and from the setup.py there's pyyaml dependency which probably should be put in requirements.txt

**Comment by sergiocorreia** [comment]
`shutilwhich` allows supporting older Py3 versions (py3.2 I think).

On the other hand `pyyaml` is for sure a requirement, but that would mean only but from the [docs](http://pyyaml.org/wiki/PyYAML#Requirements) it only supports Py2.7 and Py3.4+ which means deprecating support for Py3.3 as well.

**Comment by ickc** [comment]
For the `pyyaml`'s support on older Python: since from the tests it seems working fine, I think may be we can still keep 3.2 and 3.3 (and pypy), and remove it when there's issue?

**Pull request merged**
