### PR TITLE
Develop to master: minor changes

### PR DESCRIPTION
**Pull request by ickc**

### CODE REVIEW

**Comment by ickc** [comment]
@sergiocorreia, do you think panflute 2.0 is ready to release in this PR?

**Comment by sergiocorreia** [comment]
Yep, will merge it and then add it to pypi!

**Comment by ickc** [comment]
Thanks! You're doing all the heavy lifting after all!

**Comment by sergiocorreia** [comment]
Well we all are!

BTW, it's live now: https://pypi.org/project/panflute/

**Pull request merged**
