### PR TITLE
add a few more badges

### PR DESCRIPTION
**Pull request by ickc**
I'm not sure if you like the download count. The others are pretty standard and useful. Let me know if you want to remove the download count (or feel free to edit).

### CODE REVIEW

**Comment by sergiocorreia** [comment]
The status and PyPI version badges seem the most useful. 

Python verson is a bit misleading (as it should actually work on the 3.6 branch and pypy, but we are not requiring it for the build).

Also, unless you are Keneth Reitz or something, the dl count is low enough that I wouldn't put it.

**Comment by ickc** [comment]
In commit d50d1d9, since we expanded the supported version, it seems that in the travis build we shouldn't let those we said supported to `allow_failure`. Do you want me to change that?

**Comment by sergiocorreia** [comment]
Python 3.6 is not final yet, so even we intend to support it, if a build fails on it while it's on beta I don't want the build to appear as failing. When 3.6 final gets released (in a few months AFAIK) then we should update travis.

**Comment by ickc** [comment]
How about pypy3? I setup pypy3 to `allow_failure` too.

**Comment by sergiocorreia** [comment]
I think a similar situation applies:

> Warning: PyPy3.3 is considered alpha/beta software. All binaries are thus called “alpha”. It is known to be sometimes much slower than PyPy 2. You are welcome to use it anyway; if you're lucky it will be fast in your case. We are currently working on PyPy3.5 supporting Python 3.5.x, but it is not ready for release yet.

(From the [downloads](http://pypy.org/download.html) file)

**Pull request merged**
