### PR TITLE
added panfl CLI (with click) and added filters as modules like mod.abc

### PR DESCRIPTION
**Pull request by kiwi0fruit**
I haven't tested it yet though. I'll test it tomorrow.

* [x] test two panfl modes. See if options are click-parsed well. See if results of functions are right.
* [x] check modules filters like foo.bar
* [x] check abs path filters like c:\foo\bar.py
* [x] check --data-dir, --no-sys-path in metadata.

### CODE REVIEW

**Comment by sergiocorreia** [comment]
Overall looks great, thanks also for the refactoring. That said, two things:

1. Two tests are failing, partly because `ContextImport.init` now requires a mandatory argument `extra_dirs`. Can it be optional instead?
2. How feasible would it be to add some sort of test on the new features? Panflute uses [pytest](https://docs.pytest.org/en/latest/) which is quite easy to use (it automatically looks for files in the `test` folder named  `test_*.py`; these files just contain a bunch of asserts).

Cheers!
Sergio

**Comment by kiwi0fruit** [comment]
I still haven't tested the PR

**Comment by kiwi0fruit** [comment]
@sergiocorreia I've fixed changes. It even passes tests (but I still haven't done testing).

I also added ability to set filters by absolute path. But this would mean that the folders of the filters would be temporary prepended to the sys.path that may have unwanted consequences. I don't think that it's a problem but I suggest writing about changing sys.path in panflute pandoc filter description. So the users be aware. And also adding it the release notes.

**Comment by sergiocorreia** [comment]
Thanks for.the changes! I'll go through them tomorrow (Tuesday).

**Comment by kiwi0fruit** [comment]
@sergiocorreia I've tested manually. Looks like everything works... But I wasn't really thorough. See [TODO.txt](https://github.com/kiwi0fruit/panflute/blob/master/tests/test_panfl/TODO.txt) for what I tested. I guess this can be automated.

**Comment by sergiocorreia** [comment]
Looks good. The TravisCI failure on 2.7 is because `subprocess.run` was only added on 3.5. There are two options for that, 

1) Allow the build to fail on 2.7. First, it's a PITA to support and it will be mostly retired in [one year](https://pythonclock.org/) anyways. (Personally, it makes it harder for me to write code that I know has to support py2).
2) Rewrite it to use [`subprocess.call`](https://docs.python.org/3.8/library/subprocess.html#call-function-trio).

Both options are fine with me; just let me know which one do you prefer.

**Comment by sergiocorreia** [comment]
That would mean that only 3.6 and 3.7 are fully supported. But I'm fine with this, as long as the test failures on 2.7 and 3.5 are within the autofilter features (which is the case).

Can you add the two "allow failures line to the Travis yaml file, so I can merge the PR?

Thanks again!

**Comment by kiwi0fruit** [comment]
I d prefer to fix it a bit more. I'll let you know when to merge.

**Comment by sergiocorreia** [comment]
Sure, just let me know!

**Comment by kiwi0fruit** [comment]
@sergiocorreia I've done tests. Everything seems to work fine.

**Comment by kiwi0fruit** [comment]
@sergiocorreia Though I still don't know where to put [`panfl` description](https://github.com/kiwi0fruit/pandoctools/blob/master/docs/panfl.md). I leave this to your desision.

Please let me know after you update the package on pypi so I would update my other packages.

**Comment by kiwi0fruit** [comment]
@sergiocorreia any news?

**Comment by sergiocorreia** [comment]
We could put the markdown file in a "docs" folder and then I can try to add it to the online help.

Just to be clear, this is the final version of the PR no? (So I can merge)

**Comment by kiwi0fruit** [comment]
@sergiocorreia Yep, this is the final version.

**Comment by kiwi0fruit** [comment]
@sergiocorreia Great! Thanks for telling me.

**Comment by kiwi0fruit** [comment]
@sergiocorreia I suggest for now inserting plain html to the right place - simply link like [`see also <code>panfl</code> CLI`](https://github.com/kiwi0fruit/pandoctools/blob/master/docs/panfl.md).

**Pull request merged**
