### PR TITLE
autopep8

### PR DESCRIPTION
**Pull request by ickc**
autopep8 . --recursive --in-place --pep8-passes 2000 --verbose

### CODE REVIEW

**Comment by ickc** [comment]
This uses the autopep8 to auto cleanup the source code. Feel free to close it if you don't like autopep8 though.

**Comment by sergiocorreia** [comment]
I'll keep this on hold for now, as there are a few changes that we might not like (changing the source for the pandocfilter examples, and splitting the `py2` check in two lines)

**Comment by ickc** [comment]
I did some manual editing in addition to autopep8. In particular, check 3bfd0da on the py2 code.

Travis is also setup to check pep8 while ignoring some errors: `pep8 . --ignore=E265,E501,E701,E731`.

**Comment by sergiocorreia** [comment]
I'm a bit ambivalent about the changes. I agree that pep8 is useful, but I still think they are more of a suggestion than a rule, specially when it makes stuff harder to read 

There is a recent article by Kenneth Reitz about this: https://www.kennethreitz.org/essays/if-i-could-amend-pep-8 , and more generally, I don't trust automatic tools because they can make code harder to read: http://pep8.org/#a-foolish-consistency-is-the-hobgoblin-of-little-minds

**Comment by ickc** [comment]
To me actually after the change it's easier to read, mainly about the white spaces, more consistent "tab" spaces, and e.g. spaces around operator.

But since it is subjective and unimportant, I'll close it anyway.

**Pull request closed without merging**
