### PR TITLE
close #166: Revert "repeat for builtin2meta"

### LINKED ISSUE #166: Regression: panflute.elements.builtin2meta no longer supports subclasses of builtins
https://github.com/sergiocorreia/panflute/commit/a72ffb5b48ca2c871ad8818595cf0ae888c91f4c was first released in 2.0.3. It breaks support for converting subclasses of builtin types to pandoc meta types. This is because it stops using `isinstance` and directly compares type instead. CC @ickc 

This caused the issue mentioned at https://github.com/manubot/rootstock/pull/386#issuecomment-724926969 and https://github.com/sergiocorreia/panflute/issues/164#issuecomment-724938868:

```python-traceback
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/panflute/containers.py", line 76, in insert
    v = check_type(v, self.oktypes)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/panflute/utils.py", line 71, in check_type
    raise TypeError(msg)
TypeError: 

Element "MetaList" received "CSL_Item" but expected <class 'panflute.base.MetaValue'>
```

CSL_Item is a dict subclass.

### PR DESCRIPTION
**Pull request by ickc**
This reverts commit a72ffb5b48ca2c871ad8818595cf0ae888c91f4c.

### CODE REVIEW

**Comment by sergiocorreia** [comment]
I wouldn't go as far as revert it yet, want to understand if there is a middle point that preserves the speed and the flexibility

**Comment by ickc** [comment]
c.f. #166 

Sorry didn't foresee people subclassing those. After the discussion in #166, I think we should keep it general.

Since the comments indicates that only `from_json` is slow, but didn't mention `builtin2meta`, the trick there is nice to have but non-essential. `isinstance` is much more general (but slow).

**Comment by ickc** [comment]
For such a short if then else clause, the speed up wouldn't be much. The real slow down is from isinstance comparing to just look up type, but as long as we allow people to subclass things then there really isn't a get away.

Look up first then repeat if isinstance then else clause is going to slow down the last case.

**Comment by dhimmel** [comment]
As noted in https://github.com/sergiocorreia/panflute/issues/166#issuecomment-725720122, I am working on a fix. Would appreciate the chance to propose my PR.

**Comment by ickc** [comment]
Feel free and your call.

**Comment by sergiocorreia** [comment]
Thanks again for both of your comments.

So far it seems there are two options:

1) keep the `if tag in _res_func:` part, and at the end instead of raising `NotImplementedError`, just repeat the preexisting code. The con of this is that it would add a lot of code and when we add new elements (like Underscore) we would need to remember to add them in both places.

2) use the __bases__ function:

```python

from panflute import *

class Foo:
    pass

class Bar(Foo):
    pass

class SuperSpace(Space, Bar):
    pass


x =SuperSpace('hello')

print(type(x))
print(type(x).__bases__)
```

**Pull request closed without merging**
