### PR TITLE
Py2 refactoring: minimize the footprint of py2 code

### PR DESCRIPTION
**Pull request by ickc**
After this commit, a search on the keyword "py2" will find the lines that matter to py2 only. It will be easier to cleanup when py2 support is dropped.

### CODE REVIEW

**Comment by ickc** [comment]
I'll double check.

Reference: aa6210a, #47.

**Comment by sergiocorreia** [comment]
Btw, I altogether deleted the bugged versions, to avoid any problems.

**Comment by ickc** [comment]
I tried the code #47 on py2 with on this branch and didn't get any error. And then the Travis build is passing. I think it means it is ok?

**Comment by sergiocorreia** [comment]
Hopefully it's OK.One thing we forgot is to bump version though, but it's not that urgent

**Comment by ickc** [comment]
Yup, this one is not urgent, and supposedly has no effect on end-users — just cosmetic change in source-code.

**Pull request merged**
