### PR TITLE
utils.py: load_pandoc_*: avoid unecessary if and emit more stderr

### PR DESCRIPTION
**Pull request by ickc**

### CODE REVIEW

**Comment by sergiocorreia** [comment]
Thanks for the streamlining.

BTW, do we really want to write to debug() given that there are a few common cases where pandoc_version will be empty, that are not a problem.

Would that cause confusion?

**Comment by ickc** [comment]
Actually I'm confused since we're only support pandoc>=2.11 so it seems the env var should always be present. I thought the checking is for avoiding future breaking change, not older versions?

**Comment by sergiocorreia** [comment]
The thing is that load_pandoc() gets called on Doc.__init__(). So if you run

```python
import panflute as pf
doc = pf.Doc()
```

Then you will create a doc object with no pandoc_version, because no pandoc was involved in the creation of this `doc` object.

Further, if you create the doc file via:

```python
text = "Some markdown text"
doc = pf.convert_text(text, output_format='panflute')
```

Then `pandoc_version` will also be missing. Internally, `convert_text()` calls `run_pandoc()` which in turn calls `proc.communicate()` from the `subprocess` library. But I haven't been able to find an easy way to extract env data from `proc.communicate`.

**Comment by ickc** [comment]
Oh, right!

**Comment by ickc** [comment]
Merging as it should be resolved. I'll merge develop to master after this and we can continue there if there's remaining problem.

**Pull request merged**
