### PR TITLE
Py2 support

### PR DESCRIPTION
**Pull request by kdheepak**

### CODE REVIEW

**Comment by sergiocorreia** [comment]
Hi Dheepak, thanks for the PR!

It would be best if we separate the Python 2 commits from the two general commits (the tab and space fixes):

- The general ones can be merged trivially.
- For the Python 2 commits I'm a bit on the fence since as you say it would kill introspection. If you check the [first commits](https://github.com/sergiocorreia/panflute/commit/1221da9c3b5e163550f87348846306571eb0678b) of the project, I used to dynamically create each class (with `partial()`). This made the code smaller but killed introspection, so I ditched that approach.

Perhaps a better approach would be to have [separate branches](http://python3porting.com/strategies.html#separate-branches-for-python-2-and-python-3) for Python 2 and 3? I can give you commit access so you can push to the python2 branch freely. Given that the project is fairly stable this is probably the safest approach. We can also search for a way to pack both versions in the same python egg, so the python 2 version can also be installed from pypi.

Let me know what you think.

Best,
S

**Comment by kdheepak** [comment]
Thanks for the quick comments! I have a couple of thoughts. I believe `partial` functions will not be affected by these changes. The only change I can think of is that when a user is about to instantiate an instance of a class, and is using IPython or a IDE, the signature of functions in the pop up for help will change from

```
def function(*args, keyword1='one', keyword2='two')
```

to 

```
def function(*args, **kwargs)
```

The docstrings will still remain the same, and will be accessible to a user in both cases. 
Additionally, using metaprogramming we can add function signatures to these functions if required in the future. Also, I'll add that I don't think we should use function signatures to make sure a package works, that will cause all sorts of debugging issues down the line (mainly for future developers).

I'm slightly biased towards having a unified codebase. There are two Python3 features that are currently being used in this package
* keyword only args
* and unicode

I believe this PR addresses the first one and to a large extent the second one as well. Having a unified codebase has several advantages from a package maintaining standpoint. If we had one branch that consolidated the features of the package across versions, then any future features you add will directly be available for Python2 users. It'll make future maintenance easier, and users will definitely appreciate it.

That said, I'm completely okay with it if you decided that we should have a separate branch for Python2 and I would be more than happy to maintain it. Python3 syntax is definitely nicer. From a feature perspective, I don't believe there are any Python3 only features this package employs right now that cannot be backported, but if there are separate branches it will allow the package to go in that direction in the future. If I did maintain a separate branch, I would try to ensure Python3 maximum compatibility. 

I'll give you a chance to think about it. The TLDR is that I still recommend having a single codebase but would be happy to maintain a separate branch. Meanwhile I'll take a stab at this pull request again some time this week and get back to you.

**Comment by sergiocorreia** [comment]
What I meant is that I really care about the autocompletion, so much that I ditched the initial version of panflute (that used `partials()`).

Another concern is that the code debt this might generate: maybe 3 years down the line no one uses py2, but our code would still be uglier and longer because of the compat.

Thus, separating branches seems like the safer approach (and it shouldn't be that hard to merge commits from -master- into -python2-).

**Comment by kdheepak** [comment]
Ah that makes sense. Okay sure, let's maintain a separate working branch for Python2. It may not be feature complete all the time, but a core set of features will always work.

**Comment by sergiocorreia** [comment]
I just added you as a collaborator so you'll have push permissions. I also "cherry picked" the two pep8 commits (so I can close this pull request), and created a new python2 branch.

Feel free to push commits to python2 or branches that you create, but let me know before pushing stuff to master.

Cheers,
Sergio

**Comment by kdheepak** [comment]
Thanks! I'll add these commits to the python2 branch after looking at it more. And I'll submit pull requests to master if I think there's useful additions I can make, just so that you have a chance to review them. There's also probably an option on GitHub to protect the master branch, which may not be a bad idea.

**Comment by kdheepak** [comment]
For reference, Python2 branch will be maintained at the following URL. 

[https://github.com/sergiocorreia/panflute/tree/python2](https://github.com/sergiocorreia/panflute/tree/python2)

**Pull request closed without merging**
